name: ci-pipeline
run-name: ${{ github.actor }} is testing the commit
on: [push]
jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '17'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    - run: npm install
    - run: npm run lint-check
    - run: npm run test


